import type { Metadata } from 'next';
import { Providers } from '@/app/providers';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='m-0 box-border p-0'>
			<head>
				<meta name='viewport' content='width=device-width, initial-scale=1.0' />
				<title>{metadata.title as string}</title>
				<meta name='description' content={metadata.description as string} />
			</head>
			<body className='m-0 box-border p-0'>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
